services:
  nats:
    image: nats:2.11
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: >
      -js
      --user guest
      --pass guest
    labels:
      io.quarkus.devservices.compose.wait_for.logs: .*Server is ready.*
  lgtm:
    image: grafana/otel-lgtm
    container_name: lgtm
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3000:3000"